# frozen_string_literal: true

require 'rubicons/version'
require 'rubicons/base_icon_set'
require 'rubicons/railtie' if defined?(Rails)

module Rubicons
  # autoload :AntDesign, 'rubicons/ant_design'
  autoload :Bootstrap, 'rubicons/bootstrap'
  autoload :BoxIcons, 'rubicons/box_icons'
  autoload :CircumIcons, 'rubicons/circum_icons'
  # autoload :CssGg, 'rubicons/css_gg'
  # autoload :Devicons, 'rubicons/devicons'
  autoload :Feather, 'rubicons/feather'
  # autoload :FlatColorIcons, 'rubicons/flat_color_icons'
  autoload :FontAwesome5, 'rubicons/font_awesome5'
  autoload :FontAwesome6, 'rubicons/font_awesome6'
  # autoload :GameIcons, 'rubicons/game_icons'
  # autoload :GrommetIcons, 'rubicons/grommet_icons'
  autoload :Heroicons, 'rubicons/heroicons'
  autoload :Heroicons2, 'rubicons/heroicons2'
  # autoload :IcoMoon, 'rubicons/ico_moon'
  autoload :Ionicons4, 'rubicons/ionicons4'
  autoload :Ionicons5, 'rubicons/ionicons5'
  autoload :LineAwesome, 'rubicons/line_awesome'
  autoload :Lucide, 'rubicons/lucide'
  autoload :MaterialDesign, 'rubicons/material_design'
  autoload :Octicons, 'rubicons/octicons'
  autoload :PhosphorIcons, 'rubicons/phosphor_icons'
  autoload :Radix, 'rubicons/radix'
  autoload :RemixIcon, 'rubicons/remix_icon'
  autoload :SimpleIcons, 'rubicons/simple_icons'
  # autoload :SimpleLineIcons, 'rubicons/simple_line_icons'
  autoload :TablerIcons, 'rubicons/tabler_icons'
  autoload :ThemifyIcons, 'rubicons/themify_icons'
  autoload :Typicons, 'rubicons/typicons'
  # autoload :VsCodeIcons, 'rubicons/vs_code_icons'
  autoload :WeatherIcons, 'rubicons/weather_icons'
end
